#ifndef GITFU_VERSION_H
#define GITFU_VERSION_H

#define GITFU_VERSION_MAJOR @gitfu_VERSION_MAJOR@
#define GITFU_VERSION_MINOR @gitfu_VERSION_MINOR@
#define GITFU_VERSION_REV   @gitfu_VERSION_REV@

#define GITFU_VERSION_STR   "@gitfu_VERSION_STRING@"

#endif // GITFU_VERSION_H